=== TATJAVAPavelKlindziuk/WikiApiRetrofit2/xsd/wiki.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.klindziuk.com/wiki" xmlns:tns="http://www.klindziuk.com/wiki"
	elementFormDefault="qualified">

	<!--complex type for root element -->
	<xs:element name="wiki">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Request" type="tns:Request"
					minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Request">
                <xs:sequence>
			<xs:element name="parameter" type="xs:string" minOccurs="1"	maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="tns:Name" use="required" />
		<xs:attribute name="value" type="tns:Value" use="required" />
	</xs:complexType>


	<!--simple types for tag's attributes -->
	<xs:simpleType name="Name">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z\s.-]+" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Value">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== TATJAVAPavelKlindziuk/WikiApiRetrofit2/xml/wiki.xml
<?xml version="1.0" encoding="UTF-8"?>
<wiki xmlns="http://www.epam.klindziuk.com/wiki"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.klindziuk.com/wiki file:///C:/Users/Pavel_Klindziuk/Program_Files/eclipse/workspace/Retrofit/xsd/wiki.xsd">
<request>            
<parameter name ="action" value = "query" />    
<parameter name ="prop"   value = "revisions" />    
<parameter name ="titles" value = "Barcelona" />    
<parameter name ="rvprop" value = "timestamp|user|comment|content" />    
<parameter name ="format" value = "json" />
</request>
<request>            
<parameter name ="action" value = "query" />    
<parameter name ="prop"   value = "revisions" />    
<parameter name ="titles" value = "Minsk" />    
<parameter name ="rvprop" value = "timestamp|user|comment|content" />    
<parameter name ="format" value = "json" />
</request>    
<request>            
<parameter name ="action" value = "query" />    
<parameter name ="prop"   value = "revisions" />    
<parameter name ="titles" value = "NewYork" />    
<parameter name ="rvprop" value = "timestamp|user|comment|content" />    
<parameter name ="format" value = "json" />
</request>    
    
 </wiki>
